In [1]:
print("Image to csv conversion !!")

Image to csv conversion !!


In [5]:
import numpy as np
import os
import cv2

IMG_DIR = 'C://Users//jamie//Downloads//Extended CK+48 Dataset//FER2021 Dataset//archive//data//train//seizure'

for img in os.listdir(IMG_DIR):
        img_array = cv2.imread(os.path.join(IMG_DIR,img), cv2.IMREAD_GRAYSCALE)
        # unnecesary because imread already returns a numpy.array
        #img_array = np.array(img_array)
        img_array = (img_array.flatten())
        # add one dimension back to the array and 
        # transpose it to have the a row matrix instead of a column matrix
        img_array  = img_array.reshape(-1, 1).T
        print(img_array)
        # opening in binary and append mode
        with open('output.csv', 'ab') as f:
            # expliciting the delimiter as a comma
            np.savetxt(f, img_array, delimiter=" ")

[[214 157 203 ... 167 174 185]]
[[174 155 163 ... 139 143 147]]
[[135 127 121 ...   4  11  19]]
[[64 62 58 ...  6  6  5]]
[[39 32 26 ...  9 10 10]]
[[47 38 29 ...  9  7  4]]
[[23 28 38 ...  7  7  7]]
[[31 29 29 ...  8  9 10]]
[[28 34 42 ...  4  5  7]]
[[194 173 167 ...  17  17  18]]
[[ 68  69  75 ...  91  94 103]]
[[249 255 252 ... 129 119 106]]
[[ 34  12  27 ... 189 188 186]]
[[198 201 201 ...  29 138 126]]
[[195 196 197 ...  26  98 116]]
[[170 160 176 ...   6  14  19]]
[[183 184 185 ...  83  94 102]]
[[161 176 178 ...   0   0   0]]
[[196 206 194 ...  14   6   8]]
[[ 68  66  61 ... 121 125 128]]
[[179 190 188 ...  18   3  17]]
[[170 167 170 ...  13   8  16]]
[[179 183 169 ...   9  11  22]]
[[119 113 114 ...  18  18  18]]
[[183 168 165 ...   5  16  28]]
[[190 170 152 ...  15  14  13]]
[[184 182 170 ...   8  11  18]]
[[183 172 158 ...  16  19   0]]
[[113 212 122 ...  51  59  77]]
[[ 49  65  56 ... 118 126 130]]
[[ 92 167 175 ... 119 124 167]]
[[ 53  66 166 ... 102 107 100]]
[[ 54  61  6

[[131 124 123 ... 144 152 159]]
[[168 211 204 ...   8  11  19]]
[[197 215 213 ... 157 164  40]]
[[160 207 215 ... 127 122 116]]
[[56 46 37 ... 86 73 72]]
[[ 30  30  30 ...  42  90 156]]
[[ 99  32  35 ... 155 145 172]]
[[106  93 116 ... 105 102 105]]
[[ 84  71  59 ... 104  96  90]]
[[ 98 123 108 ... 101 103 103]]
[[117  93  89 ...  91  94 109]]
[[198 118 100 ... 171 133  95]]
[[ 36  67  63 ... 163 164 165]]
[[132 110  86 ... 125 140 168]]
[[156 204 181 ... 172 146 103]]
[[ 73  78  77 ... 168 170 172]]
[[ 69  66  67 ... 165 169 171]]
[[ 76  75  73 ... 170 173 174]]
[[ 20   9  39 ... 148 150 146]]
[[ 38  78 103 ... 159 159  10]]
[[  9  26  46 ... 147 148 152]]
[[171 171 172 ... 197 212 114]]
[[ 45  34  38 ... 152 147 144]]
[[166 161 157 ...  47  49  52]]
[[ 46  41  43 ... 200 205 211]]
[[154 152 152 ...  61  66  68]]
[[101 160 187 ...  51  50  50]]
[[ 78  63  59 ... 168 172 175]]
[[ 86  83  90 ... 115 102  90]]
[[137 133 127 ...  39  58  75]]
[[134 135 137 ...  66  65  62]]
[[132 134 136 